services:
  newsnow:
    image: kayparavel/newsnow-kayparavel:latest
    container_name: newsnow
    ports:
      - '14444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=
      # 启用 Node.js 内置代理支持
      - NODE_USE_ENV_PROXY=1
      # 代理配置（取消注释并修改为您的代理地址）
      - HTTP_PROXY=http://ip:port
      - HTTPS_PROXY=http://ip:port
      - PROXY=http://ip:port
    restart: always

volumes:
  newsnow_data:
    name: newsnow_data
