/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CarouselEditorImport } from './routes/carousel-editor'
import { Route as CarouselImport } from './routes/carousel'
import { Route as IndexImport } from './routes/index'
import { Route as CColumnImport } from './routes/c.$column'

// Create/Update Routes

const CarouselEditorRoute = CarouselEditorImport.update({
  id: '/carousel-editor',
  path: '/carousel-editor',
  getParentRoute: () => rootRoute,
} as any)

const CarouselRoute = CarouselImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CColumnRoute = CColumnImport.update({
  id: '/c/$column',
  path: '/c/$column',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/carousel': {
      id: '/carousel'
      path: '/carousel'
      fullPath: '/carousel'
      preLoaderRoute: typeof CarouselImport
      parentRoute: typeof rootRoute
    }
    '/carousel-editor': {
      id: '/carousel-editor'
      path: '/carousel-editor'
      fullPath: '/carousel-editor'
      preLoaderRoute: typeof CarouselEditorImport
      parentRoute: typeof rootRoute
    }
    '/c/$column': {
      id: '/c/$column'
      path: '/c/$column'
      fullPath: '/c/$column'
      preLoaderRoute: typeof CColumnImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carousel': typeof CarouselRoute
  '/carousel-editor': typeof CarouselEditorRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carousel': typeof CarouselRoute
  '/carousel-editor': typeof CarouselEditorRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/carousel': typeof CarouselRoute
  '/carousel-editor': typeof CarouselEditorRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carousel' | '/carousel-editor' | '/c/$column'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carousel' | '/carousel-editor' | '/c/$column'
  id: '__root__' | '/' | '/carousel' | '/carousel-editor' | '/c/$column'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarouselRoute: typeof CarouselRoute
  CarouselEditorRoute: typeof CarouselEditorRoute
  CColumnRoute: typeof CColumnRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarouselRoute: CarouselRoute,
  CarouselEditorRoute: CarouselEditorRoute,
  CColumnRoute: CColumnRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/carousel",
        "/carousel-editor",
        "/c/$column"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/carousel": {
      "filePath": "carousel.tsx"
    },
    "/carousel-editor": {
      "filePath": "carousel-editor.tsx"
    },
    "/c/$column": {
      "filePath": "c.$column.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
